// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ2axXsvNszQ_F884L2E5u6PnXGuut3MQ',
    appId: '1:77952150561:web:c1836f87bacf3633694760',
    messagingSenderId: '77952150561',
    projectId: 'sweetmeproject',
    authDomain: 'sweetmeproject.firebaseapp.com',
    storageBucket: 'sweetmeproject.appspot.com',
    measurementId: 'G-2HKQRPS8RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-b-FXAl_FjTnWL5NR76vxQ1StfLHqrJA',
    appId: '1:77952150561:android:4f9aa3a5fdf9198b694760',
    messagingSenderId: '77952150561',
    projectId: 'sweetmeproject',
    storageBucket: 'sweetmeproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB36NAQ3y--SKWLyoaZcPQjV5LNaT_4Of0',
    appId: '1:77952150561:ios:33a54c0029de3bd2694760',
    messagingSenderId: '77952150561',
    projectId: 'sweetmeproject',
    storageBucket: 'sweetmeproject.appspot.com',
    iosBundleId: 'com.example.plowProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB36NAQ3y--SKWLyoaZcPQjV5LNaT_4Of0',
    appId: '1:77952150561:ios:4062de57b1c37ce2694760',
    messagingSenderId: '77952150561',
    projectId: 'sweetmeproject',
    storageBucket: 'sweetmeproject.appspot.com',
    iosBundleId: 'com.example.plowProject.RunnerTests',
  );
}
